# Generated by Django 5.0 on 2023-12-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
