# Generated by Django 5.0 on 2023-12-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='v_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='v_messege',
            new_name='messege',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='v_name',
            new_name='name',
        ),
    ]
